apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-yeller.fullname" . }}
  labels:
    {{- include "go-yeller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "go-yeller.selectorLabels" . | nindent 4 }}
