# Default values for go-yeller on staging env.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
replicaCount: 1

image:
  repository: eu.gcr.io/akecld-saas-training/go-yeller
  pullPolicy: IfNotPresent
  tag: 0.0.1

config:
  port: 8888

ingress:
  hosts:
    - host: goyeller.training.cloud.akeneo.com
      paths:
        - pathType: ImplementationSpecific
  tls:
    - hosts:
        - goyeller.training.cloud.akeneo.com

