# Default values for go-yeller on staging env.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: eu.gcr.io/akecld-saas-training/go-yeller-staging
  pullPolicy: IfNotPresent
  tag: 0.0.1-905daff20d290161f0e6a71f7f4827de379602dd
config:
  port: 8888
