# Default values for go-yeller on staging env.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: eu.gcr.io/akecld-saas-training/go-yeller-staging
  pullPolicy: IfNotPresent
  tag: 0.0.1-31b7410ebfe101fa9578f83bf2b4d5c2e470366b
config:
  port: 8888
