# Default values for go-yeller on staging env.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
replicaCount: 1
image:
  repository: eu.gcr.io/akecld-saas-training/go-yeller-staging
  pullPolicy: IfNotPresent
  tag: 0.0.2-8de646ec3119bb7bee2e7ba41d9cca5c22fec3ad
config:
  port: 8888
ingress:
  hosts:
    - host: goyeller-staging.training.cloud.akeneo.com
      paths:
        - pathType: ImplementationSpecific
  tls:
    - hosts:
        - goyeller-staging.training.cloud.akeneo.com
